// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo9DBtsIZeH05A9q7R1BGfIO2Tj6t5jys',
    appId: '1:699055695394:web:51d2d9729617e257134c7b',
    messagingSenderId: '699055695394',
    projectId: 'chat-app-8dbd4',
    authDomain: 'chat-app-8dbd4.firebaseapp.com',
    storageBucket: 'chat-app-8dbd4.appspot.com',
    measurementId: 'G-MVRFYNGE2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQToh1UmnuRcPJ3ehN8F1A6uB1NSBFTrE',
    appId: '1:699055695394:android:8f37be79df08bbf8134c7b',
    messagingSenderId: '699055695394',
    projectId: 'chat-app-8dbd4',
    storageBucket: 'chat-app-8dbd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2VTBQsVHvtc79jnjx2uwoLvozsDuwjac',
    appId: '1:699055695394:ios:ed47f8f491923e12134c7b',
    messagingSenderId: '699055695394',
    projectId: 'chat-app-8dbd4',
    storageBucket: 'chat-app-8dbd4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2VTBQsVHvtc79jnjx2uwoLvozsDuwjac',
    appId: '1:699055695394:ios:ed47f8f491923e12134c7b',
    messagingSenderId: '699055695394',
    projectId: 'chat-app-8dbd4',
    storageBucket: 'chat-app-8dbd4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo9DBtsIZeH05A9q7R1BGfIO2Tj6t5jys',
    appId: '1:699055695394:web:4e18049991795608134c7b',
    messagingSenderId: '699055695394',
    projectId: 'chat-app-8dbd4',
    authDomain: 'chat-app-8dbd4.firebaseapp.com',
    storageBucket: 'chat-app-8dbd4.appspot.com',
    measurementId: 'G-P95LGVN2C8',
  );
}
